# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170627_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='dsec',
            new_name='desc',
        ),
    ]
