# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20170724_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='what_you_learn',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='you_need_know',
        ),
    ]
