# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='\u6570\u636eID'),
        ),
    ]
