# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.CharField(default='', max_length=100, verbose_name='\u77e5\u8bc6\u83b7\u53d6'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='', max_length=100, verbose_name='\u8bfe\u524d\u987b\u77e5'),
        ),
    ]
