# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20170724_1501'),
        ('courses', '0008_auto_20170724_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u8bfe\u7a0b\u8001\u5e08'),
        ),
    ]
